version: "3.9"
services:
  mysql:
    image: mariadb:10.11.2
    volumes:
      - mysql-data:/var/lib/mysql
    container_name: bt_mysql
    # Uncomment below when on Mac M1
    # platform: linux/arm64/v8
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MYSQL_USER: bt
      MYSQL_PASSWORD: bt
      DATABASE_NAME: bt
    ports:
      - 3306:3306
    env_file:
      - .env
volumes:
  mysql-data: